### ISSUE TITLE
Error trying snakemake pipeline from google-cloud service

### ISSUE THREAD

**Issue by novitch** [yesimon/metax_bakeoff_2019#2]
Hi, I wanted to reproduce the results and test my data with your pipeline, but infortunately I am in difficulty with th snakemake process:
````
snakemake download_src
...
OSError in line 2 of /home/matalb01/metax_bakeoff_2019/rules/download.smk:
Project was not passed and could not be determined from the environment.
  File "/home/matalb01/metax_bakeoff_2019/Snakefile", line 102, in <module>
  File "/home/matalb01/metax_bakeoff_2019/rules/download.smk", line 2, in <module>
  File "/home/matalb01/anaconda2/envs/metax/lib/python3.6/site-packages/snakemake/remote/GS.py", line 28, in __init__
  File "/home/matalb01/anaconda2/envs/metax/lib/python3.6/site-packages/google/cloud/storage/client.py", line 94, in __init__
  File "/home/matalb01/anaconda2/envs/metax/lib/python3.6/site-packages/google/cloud/client.py", line 226, in __init__
  File "/home/matalb01/anaconda2/envs/metax/lib/python3.6/site-packages/google/cloud/client.py", line 181, in __init__
````

I looked into the snakemake help for google storage and did what they recommand:
````
gcloud auth application-default login
````

How to fix this error? Should set a project name somewhere?

Thanks,

**Comment by novitch** [comment]
ok fixed it. I was "metax"

**Comment by MajoroMask** [comment]
> ok fixed it. I was "metax"

Hi @novitch , can you explain more on how you fixed it? I've encountered the same error and I'm not familiar with google cloud. Thanks a lot!

**Comment by novitch** [comment]
Hello @MajoroMask , 
I really don't remember what it was, sorry for the lack of explanation. I do not have the conda env anymore.
It looks like I had to set a variable "Project" somewhere and the name was "metax"
/home/matalb01/metax_bakeoff_2019/rules/download.smk

**Comment by MajoroMask** [comment]
> Hello @MajoroMask , I really don't remember what it was, sorry for the lack of explanation. I do not have the conda env anymore. It looks like I had to set a variable "Project" somewhere and the name was "metax" /home/matalb01/metax_bakeoff_2019/rules/download.smk

OK I'll try searching docs and other sources based on this. Thanks for your reply!

**Comment by MajoroMask** [comment]
> > ok fixed it. I was "metax"
> 
> Hi @novitch , can you explain more on how you fixed it? I've encountered the same error and I'm not familiar with google cloud. Thanks a lot!

For anyone who is also interested in this, I somehow managed gain access to the data used in this study by directly download from google storage:

```bash
gsutil -m cp 'gs://metax-bakeoff-2019/fastq/*.fastq.bz2' ./fastq
```

I did not download the database files but I think this method can be applied, too.
